name: pytng
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - cython
  - zlib
  - sphinx
  - pytest
  - pytest-cov
  - pip
  # docs
  - mdanalysis-sphinx-theme >=1.0.1
  - pip:
      - sphinx-sitemap
