[build-system]
# Minimum requirements for the build system to execute
requires = [
    "cython>=0.28,<3.0",
    "setuptools",
    "wheel",
    # below matches MDA
    "numpy==1.20.0; python_version=='3.8' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_python_implementation != 'PyPy'",
    "numpy==1.20.0; python_version=='3.9' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_python_implementation != 'PyPy'",
    # arm64 on darwin for py3.8+ requires numpy >=1.21.0
    "numpy==1.21.0; python_version=='3.8' and platform_machine=='arm64' and platform_system=='Darwin' and platform_python_implementation != 'PyPy'",
    "numpy==1.21.0; python_version=='3.9' and platform_machine=='arm64' and platform_system=='Darwin' and platform_python_implementation != 'PyPy'",
    # Scipy: On windows avoid 1.21.6, 1.22.0, and 1.22.1 because they were built on vc142
    "numpy==1.22.3; python_version=='3.10' and platform_system=='Windows' and platform_python_implementation != 'PyPy'",
    # As per https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg
    # safest to build at 1.21.6 for all other platforms
    "numpy==1.21.6; python_version=='3.10' and platform_system !='Windows'and platform_python_implementation != 'PyPy'",
    "numpy==1.23.2; python_version=='3.11' and platform_python_implementation != 'PyPy'",
    "numpy<2.0; python_version>='3.12'",
]