# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # 3 am Tuesdays and Fridays
    - cron: "0 3 * * 2,5"
    
concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 12
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
         python-version: ${{ matrix.python-version }}
         auto-update-conda: true
         #channels: conda-forge
         #mamba-version: "*"
         environment-file: environment.yaml
         activate-environment: pytng
         auto-activate-base: false
    - name: Check Env
      # check if we can just activate the env directly
      run: conda activate pytng
    - name: Install Pytng
      run: |
        python setup.py install
    - name: Test with pytest
      run: |
        pytest -v -ra ./tests/
